# config:
#   importPath: /git/config/6.0/identity-platform-examples/am-ds
#   exportPath: /tmp/amster

# version: 6.5.0

# For production set CPU limits to help Kube Schedule the pods.
resources:
 limits:
   memory: 756Mi
 requests:
   memory: 756Mi
