

config:
  claim: frconfig
  #importPath: /git/config/6.5/smoke-tests/am/
  importPath: /git/config/6.5/default/am/empty-import



# For production set CPU limits to help Kube Schedule the pods.
resources:
 limits:
   memory: 756Mi
 requests:
   memory: 756Mi
