image:
  repository: gcr.io/forgerock-io/ds
  #repository: gcr.io/engineering-devops/ds
  tag: 6.5.2
  pullPolicy: Always
  
gcs:
  enabled: false
  bucket: gs://forgeops/dj-backup/m-cluster
  
s3:
  enabled: false
  bucket: s3://forgeops/dj-backup

nfs:
  server: 10.201.33.74
  path: /export

backup:
  enabled: false
  pvcName: ds-backup
  storageSize: 100Gi

createPVC: false

slackUrl: undefined
