image:
  repository: registry.gitlab.com/swissid/forgeops/openam

resources:
  limits:
#    cpu: 3000m
    memory:
  requests:
#    cpu: 2000m
    memory: 

catalinaOpts: >
  -server -Xms2g -Xmx2g -XX:+UseG1GC -XX:+UseNUMA -XX:+UseCompressedOops
  -XX:MaxGCPauseMillis=200 -XX:G1MixedGCCountTarget=6 -XX:MetaspaceSize=128m
  -XX:+PrintGCApplicationStoppedTime -XX:+PrintFlagsFinal
  -XX:+ParallelRefProcEnabled -XX:InitiatingHeapOccupancyPercent=70
  -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true
  -Dcom.sun.identity.util.debug.provider=com.sun.identity.shared.debug.impl.StdOutDebugProvider
  -Dcom.sun.identity.shared.debug.file.format='%PREFIX% %MSG%\\n%STACKTRACE%'
  -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+PrintGCDetails
  -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -XX:+PrintTenuringDistribution
  -Xloggc:/tmp/gc.log -Duser.home=/home/forgerock
