
config:
  claim: frconfig
  #importPath: /git/config/6.0/default/am/empty-import
  importPath: /git/config/6.0/identity-platform-examples/am-ds
  #exportPath: /tmp/amster
  exportPath:  /git/config/default/am/export

# Amster tag that will get replaced
version: 6.0.0

# For production set CPU limits to help Kube Schedule the pods.
resources:
 limits:
   memory: 756Mi
 requests:
   memory: 756Mi