image:
  #repository: forgerock-docker-public.bintray.io/forgerock/ds
  #repository: gcr.io/engineering-devops/ds
  repository: registry.gitlab.com/swissid/$CI_PROJECT_NAME/ds

instance: configstore

configstore:
  enabled: true

replicas: $CONFIGSTORE_REPLICAS

#resources:
#  limits:
#    cpu: 1000m
#    memory: 1Gi
#  requests:
#    cpu: 1000m
#    memory: 1Gi

storageSize: 1Gi
#storageClass: fast
persistence: false

topologyKey: "kubernetes.io/hostname"
podAntiAffinity: $CONFIGSTORE_AFFINITY

backup:
#  pvcClaimName: ds-backup
  clusterName: dev
  verify: false

# If existing database is found then restore is always skipped
restore:
  enabled: false

securityContext:
