image:
  #repository: forgerock-docker-public.bintray.io/forgerock/openam
  #repository: gcr.io/engineering-devops/openam
  repository: registry.gitlab.com/swissid/$CI_PROJECT_NAME/openam

resources:
  limits:
#    cpu: 3000m
    memory: 2Gi
  requests:
#    cpu: 2000m
    memory: 2Gi

catalinaOpts: >
  -server -Xms2g -Xmx2g -XX:+UseG1GC -XX:+UseNUMA -XX:+UseCompressedOops
  -XX:MaxGCPauseMillis=200 -XX:G1MixedGCCountTarget=6 -XX:MetaspaceSize=128m
  -XX:+PrintGCApplicationStoppedTime -XX:+PrintFlagsFinal
  -XX:+ParallelRefProcEnabled -XX:InitiatingHeapOccupancyPercent=70
  -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true
  -Dcom.sun.identity.util.debug.provider=com.sun.identity.shared.debug.impl.StdOutDebugProvider
  -Dcom.sun.identity.shared.debug.file.format='%PREFIX% %MSG%\\n%STACKTRACE%'
  -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+PrintGCDetails
  -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -XX:+PrintTenuringDistribution
  -Xloggc:/tmp/gc.log -Duser.home=/home/forgerock

# Openshift does not know about Ingress
ingress:
  enabled: false

route:
  enabled: true
