domain: .example.com

fqdn: login.eng.example.com

gitImage:
  repository: eu.gcr.io/swissid-cloud/git
  tag: 6.5.0
  pullPolicy: Always

utilImage:
  repository: eu.gcr.io/swissid-cloud/util
  tag: 6.5.0
  pullPolicy: Always

# Install passwords.
amadminPassword: password
encryptionKey: "123456789012"
policyAgentPassword: Passw0rd
