image:
  repository: registry.gitlab.com/swissid/forgeops/ds

instance: ctsstore

cts:
  enabled: true

replicas: 2

resources:
  limits:
#    cpu: 1000m
    memory: 5Gi
  requests:
#    cpu: 1000m
    memory: 3Gi

storageSize: 20Gi
#storageClass: fast
persistence: false

topologyKey: "kubernetes.io/hostname"
podAntiAffinity: hard

backup:
#  pvcClaimName: ds-backup
  clusterName: prod
  verify: false

# If existing database is found then restore is always skipped
restore:
  enabled: false

securityContext:

# For JDK 8
opendjJavaArgs: >
  -server -Xms3g -Xmx3g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA
  -XX:MaxGCPauseMillis=100 -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps
  -XX:+PrintGCDetails -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -Xloggc:/tmp/gc.log

# JDK 8 additional settings from Post SwissID
#  -d64 -XX:NewSize=512M -XX:MaxNewSize=512M -XX:+UseCompressedOops -XX:MaxTenuringThreshold=1 -XX:+UseConcMarkSweepGC -XX:+UseStringDeduplication -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=20 -XX:GCLogFileSize=1M -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heap_dump.hprof"

# For JDK 11
#opendjJavaArgs: >
#  -server -Xms3g -Xmx3g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA
#  -XX:MaxGCPauseMillis=100 -verbose:gc -Xlog:gc:/tmp/gc.log
