image:
  repository: forgerock-docker-public.bintray.io/forgerock/ds
  tag: 6.5.0
  pullPolicy: IfNotPresent
  
instance: configstore

configstore:
  enabled: true

cts:
  enabled: false

userstore:
  enabled: false

idmRepo:
  enabled: false

resources:
  limits:
    memory: 2Gi
  requests:
    memory: 1Gi

replicas: 2

topologyKey: "failure-domain.beta.kubernetes.io/zone"

podAntiAffinity: hard