image:
  #repository: forgerock-docker-public.bintray.io/forgerock/ds
  #repository: gcr.io/engineering-devops/ds
  repository: eu.gcr.io/swissid-cloud/ds
  tag: 6.5.0
  pullPolicy: Always

instance: ctsstore

configstore:
  enabled: false

cts:
  enabled: true

userstore:
  enabled: false

idmRepo:
  enabled: false

resources:
  limits:
    memory: 5Gi
  requests:
    memory: 3Gi

storageSize: 20Gi
storageClass: fast

# For JDK 8
opendjJavaArgs: >
  -server -Xms3g -Xmx3g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA
  -XX:MaxGCPauseMillis=100 -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps
  -XX:+PrintGCDetails -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -Xloggc:/tmp/gc.log

# JDK 8 additional settings from Post SwissID
#  -d64 -XX:NewSize=512M -XX:MaxNewSize=512M -XX:+UseCompressedOops -XX:MaxTenuringThreshold=1 -XX:+UseConcMarkSweepGC -XX:+UseStringDeduplication -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=20 -XX:GCLogFileSize=1M -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heap_dump.hprof"

# For JDK 11
#opendjJavaArgs: >
#  -server -Xms3g -Xmx3g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA
#  -XX:MaxGCPauseMillis=100 -verbose:gc -Xlog:gc:/tmp/gc.log


replicas: 1

topologyKey: "failure-domain.beta.kubernetes.io/zone"

podAntiAffinity: soft

backup:
#  pvcClaimName: ds-backup
  clusterName: dev
  verify: false

# If existing database is found then restore is always skipped
restore:
  enabled: false
