image:
  repository: registry.gitlab.com/swissid/$CI_PROJECT_NAME/amster

config:
  importPath: /git/config/6.5/default/am/empty-import
  exportPath: /tmp/amster

amadminPassword: "$AMADMIN_PASSWORD"

# https://backstage.forgerock.com/docs/amster/6.5/user-guide/#sec-installam-reference
# Specifies the encryption key value that is used to encrypt passwords in the AM instance. For example O6QWwHPO4os+zEz3Nqn/2daAYWyiFE32.
# If you are installing an AM instance that will be making use of exiting data in a data store, you must provide the same encryption key value originally used to encrypt the passwords in those stores.
# ********** MUST be the SAME as in Post installation (???) **********
encryptionKey: "$AM_PWD_ENCRYPTION_KEY"

policyAgentPassword: "$POLICY_AGENT_PASSWORD"

configStore:
  # type can be dirServer or embedded. Only dirServer is supported
  type: dirServer
   # If type is set to embedded, the attributes below are ignored.
  #suffix:  "dc=openam,dc=forgerock,dc=org"
  suffix:  "$CONFIGSTORE_BASE_DN"
  # This is the first StatefulSet name of the configstore:
  host: configstore-0.configstore
  port: 1389
  #dirManager: "cn=Directory Manager"
  dirManager: "uid=am-config,ou=admins,$CONFIGSTORE_BASE_DN"
  adminPort: 4444
  password: "$CONFIGSTORE_PASSWORD"

userStore:
  suffix: "$USERSTORE_BASE_DN"
  # If userstore is deployed as well but empty import configuration
  # is used, override this to userstore-0.userstore to use that store
  host: userstore-0.userstore
  port: 1389
  dirManager: "uid=am-identity-bind-account,ou=admins,$USERSTORE_BASE_DN"
  password: "password-us"
  storeType: "LDAPv3ForOpenDS"

# For production set CPU limits to help Kube Schedule the pods.
resources:
 limits:
   memory: 1Gi
 requests:
   memory: 1Gi
