image:
  #repository: forgerock-docker-public.bintray.io/forgerock/amster
  #repository: gcr.io/engineering-devops/amster
  repository: registry.gitlab.com/swissid/$CI_PROJECT_NAME/amster

config:
  importPath: /git/config/6.5/default/am/empty-import
  exportPath: /tmp/amster

ctsStores: ctsstore-0.ctsstore:1389,ctsstore-1.ctsstore:1389

# Install passwords
ctsPassword: password
amadminPassword: password
encryptionKey: "123456789012"
policyAgentPassword: Passw0rd

# For production set CPU limits to help Kube Schedule the pods.
resources:
 limits:
   memory: 756Mi
 requests:
   memory: 756Mi
