image:
#  repository: forgerock-docker-public.bintray.io/ds
#  repository: gcr.io/engineering-devops/ds
  repository: registry.gitlab.com/swissid/$CI_PROJECT_NAME/ds
  tag: $VERSION
  pullPolicy: Always

gcs:
  enabled: false
  bucket: gs://swissid-backup-archive/dj-backup/$CI_ENVIRONMENT_SLUG

s3:
  enabled: false
  bucket: s3://forgeops/dj-backup/$CI_ENVIRONMENT_SLUG

nfs:
  server: 10.92.22.138
  path: /export

backup:
  pvcName: ds-backup
  storageSize: 100Gi

createPVC: true

slackUrl: undefined

securityContext:
