image:
  #repository: forgerock-docker-public.bintray.io/forgerock/ds
  #repository: gcr.io/engineering-devops/ds
  repository: docker-registry.default.svc:5000/sws-registry/ds
  tag: 6.5.0
  pullPolicy: Always

instance: ctsstore

configstore:
  enabled: false

cts:
  enabled: true

userstore:
  enabled: false

idmRepo:
  enabled: false

resources:
  limits:
    memory: 5Gi
  requests:
    memory: 3Gi

storageSize: 10Gi
storageClass: fast

persistence: false

# For JDK 8
opendjJavaArgs: >
  -server -Xms3g -Xmx3g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA
  -XX:MaxGCPauseMillis=100 -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps
  -XX:+PrintGCDetails -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -Xloggc:/tmp/gc.log

# For JDK 11
#opendjJavaArgs: >
#  -server -Xms3g -Xmx3g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA
#  -XX:MaxGCPauseMillis=100 -verbose:gc -Xlog:gc:/tmp/gc.log


replicas: 1

topologyKey: "kubernetes.io/hostname"

podAntiAffinity: soft

backup:
#  pvcClaimName: ds-backup
  clusterName: sws-tom3
  verify: false

# If existing database is found then restore is always skipped
restore:
  enabled: false

# empty security context for Openshift
securityContext:
