image:
  repository: gcr.io/forgerock-io/ds
  #repository: gcr.io/engineering-devops/ds
  tag: 6.5.2
  pullPolicy: Always

instance: ctsstore

configstore:
  enabled: false

cts:
  enabled: true

userstore:
  enabled: false

idmRepo:
  enabled: false

resources:
  limits:
    memory: 5Gi
  requests:
    memory: 3Gi

storageSize: 100Gi
storageClass: fast

# For JDK 8
opendjJavaArgs: >
  -server -Xms3g -Xmx3g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA 
  -XX:MaxGCPauseMillis=100 -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps 
  -XX:+PrintGCDetails -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -Xloggc:/tmp/gc.log

# For JDK 11
#opendjJavaArgs: >
#  -server -Xms3g -Xmx3g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA  
#  -XX:MaxGCPauseMillis=100 -verbose:gc -Xlog:gc:/tmp/gc.log


podAntiAffinity: hard

runPostSetupJob: false

replicas: 2

topologyKey: "failure-domain.beta.kubernetes.io/zone"
backup:
#  pvcClaimName: ds-backup
  clusterName: prod
  verify: false

# If existing database is found then restore is always skipped
restore:
  enabled: false
