image:
  repository: gcr.io/forgerock-io/ds
  #repository: gcr.io/engineering-devops/ds
  tag: 6.5.2
  pullPolicy: Always

instance: userstore

configstore:
  enabled: false

cts:
  enabled: false

userstore:
  enabled: true

idmRepo:
  enabled: false

resources:
  limits:
    cpu: 3000m
    memory: 5Gi
  requests:
    cpu: 1500m
    memory: 3Gi


# For JDK 8
opendjJavaArgs: >
  -server -Xms3g -Xmx3g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA 
  -XX:MaxGCPauseMillis=100 -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps 
  -XX:+PrintGCDetails -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -Xloggc:/tmp/gc.log
  
# For JDK 11
#opendjJavaArgs: >
#  -server -Xms3g -Xmx3g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA  
#  -XX:MaxGCPauseMillis=100 -verbose:gc -Xlog:gc:/tmp/gc.log


storageSize: 100Gi
storageClass: fast

replicas: 2

topologyKey: "failure-domain.beta.kubernetes.io/zone"

podAntiAffinity: hard

backup:
#  pvcClaimName: ds-backup
  clusterName: prod
  verify: false

# If existing database is found then restore is always skipped
restore:
  enabled: false