image:
  #repository: forgerock-docker-public.bintray.io/forgerock/ds
  #repository: gcr.io/engineering-devops/ds
  repository: eu.gcr.io/swissid-cloud/ds
  tag: 6.5.0
  pullPolicy: Always

instance: configstore

configstore:
  enabled: true

cts:
  enabled: false

userstore:
  enabled: false

idmRepo:
  enabled: false

resources:
  limits:
    memory: 1Gi
  requests:
    memory: 1Gi

replicas: 2

topologyKey: "failure-domain.beta.kubernetes.io/zone"

podAntiAffinity: hard

backup:
#  pvcClaimName: ds-backup
  clusterName: int
  verify: false

# If existing database is found then restore is always skipped
restore:
  enabled: false
