frconfig:
  config:
    name: frconfig
  domain: .example.com
  fqdn: login.eng.example.com
  git:
    #repo: git@github.com:tofele/forgeops-init.git
    repo: "https://github.com/tofele/forgeops-init.git"
    branch: master
  certmanager:
    enabled: true
    issuer: ca-issuer
    issuerKind: Issuer
    # For lets encrypt use this:
    #acme: true
    #issuer: letsencrypt-prod
    #issuerKind: ClusterIssuer

configstore:
  image:
    #repository: forgerock-docker-public.bintray.io/forgerock/ds
    repository: eu.gcr.io/swissid-cloud/ds
    tag: 6.5.0
    pullPolicy: Always
  instance: configstore
  configstore:
    enabled: true
  cts:
    enabled: false
  userstore:
    enabled: false
  idm:
    enabled: false
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 1Gi
  replicas: 2
  persistence: true
  podAntiAffinity: hard
  topologyKey: "failure-domain.beta.kubernetes.io/zone"
  backup:
    #pvcClaimName: ds-backup
    clusterName: eng
    verify: false
  restore:
    enabled: false

userstore:
  image:
    #repository: forgerock-docker-public.bintray.io/forgerock/ds
    repository: eu.gcr.io/swissid-cloud/ds
    tag: 6.5.0
    pullPolicy: Always
  instance: userstore
  configstore:
    enabled: false
  cts:
    enabled: false
  userstore:
    enabled: true
  idm:
    enabled: false
  resources:
    limits:
      cpu: 3000m
      memory: 5Gi
    requests:
      cpu: 1500m
      memory: 3Gi
  opendjJavaArgs: >
    -server -Xms3g -Xmx3g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA
    -XX:MaxGCPauseMillis=100 -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps
    -XX:+PrintGCDetails -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -Xloggc:/tmp/gc.log
  storageSize: 20Gi
  storageClass: fast
  replicas: 2
  persistence: true
  podAntiAffinity: hard
  topologyKey: "failure-domain.beta.kubernetes.io/zone"
  backup:
    #pvcClaimName: ds-backup
    clusterName: eng
    verify: false
  restore:
    enabled: false

ctsstore:
  image:
    #repository: forgerock-docker-public.bintray.io/forgerock/ds
    repository: eu.gcr.io/swissid-cloud/ds
    tag: 6.5.0
    pullPolicy: Always
  instance: ctsstore
  configstore:
    enabled: false
  cts:
    enabled: true
  userstore:
    enabled: false
  idm:
    enabled: false
  resources:
    limits:
      memory: 5Gi
    requests:
      memory: 3Gi
  opendjJavaArgs: >
    -server -Xms3g -Xmx3g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA
    -XX:MaxGCPauseMillis=100 -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps
    -XX:+PrintGCDetails -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -Xloggc:/tmp/gc.log
  storageSize: 20Gi
  storageClass: fast
  replicas: 2
  persistence: true
  podAntiAffinity: hard
  topologyKey: "failure-domain.beta.kubernetes.io/zone"
  backup:
    #pvcClaimName: ds-backup
    clusterName: eng
    verify: false
  restore:
    enabled: false

openam:
  image:
    #repository: forgerock-docker-public.bintray.io/forgerock/openam
    repository: eu.gcr.io/swissid-cloud/openam
    tag: 6.5.0
    pullPolicy: Always
  domain: .example.com
  fqdn: login.eng.example.com
  config:
    name: frconfig
    strategy: git
  openamReplicaCount: 1
  resources:
    limits:
      cpu: 3000m
      memory: 5Gi
    requests:
      cpu: 2000m
      memory: 4Gi
  catalinaOpts: >
    -server -Xms4g -Xmx4g -XX:+UseG1GC -XX:+UseNUMA -XX:+UseCompressedOops
    -XX:MaxGCPauseMillis=200 -XX:G1MixedGCCountTarget=6 -XX:MetaspaceSize=128m
    -XX:+PrintGCApplicationStoppedTime -XX:+PrintFlagsFinal
    -XX:+ParallelRefProcEnabled -XX:InitiatingHeapOccupancyPercent=70
    -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true
    -Dcom.sun.identity.util.debug.provider=com.sun.identity.shared.debug.impl.StdOutDebugProvider
    -Dcom.sun.identity.shared.debug.file.format='%PREFIX% %MSG%\\n%STACKTRACE%'
    -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+PrintGCDetails
    -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -XX:+PrintTenuringDistribution
    -Xloggc:/tmp/gc.log

amster:
  domain: .example.com
  image:
    #repository: forgerock-docker-public.bintray.io/forgerock/amster
    repository: eu.gcr.io/swissid-cloud/amster
    tag: 6.5.0
    pullPolicy: Always
  config:
    #importPath: /git/config/6.5/cdm/m-cluster/am
    importPath: /git/config/6.5/default/am/empty-import
    #importPath: /git/config/6.5/smoke-tests/am
    exportPath: /tmp/amster
  ctsStores: ctsstore-0.ctsstore:1389,ctsstore-1.ctsstore:1389
  ctsPassword: password
  resources:
   limits:
     memory: 756Mi
   requests:
     memory: 756Mi
