domain: .example.com

fqdn: login.sws-tom2.example.com

gitImage:
  repository: docker-registry.default.svc:5000/sws-registry/git
  tag: 6.5.0
  pullPolicy: Always

utilImage:
  repository: docker-registry.default.svc:5000/sws-registry/util
  tag: 6.5.0
  pullPolicy: Always

# Install passwords.
amadminPassword: password
encryptionKey: "123456789012"
policyAgentPassword: Passw0rd
