image:
  #repository: forgerock-docker-public.bintray.io/forgerock/ds
  #repository: gcr.io/engineering-devops/ds
  repository: docker-registry.default.svc:5000/sws-registry/ds
  tag: 6.5.0
  pullPolicy: Always

instance: configstore

configstore:
  enabled: true

cts:
  enabled: false

userstore:
  enabled: false

idmRepo:
  enabled: false

resources:
  limits:
    memory: 1Gi
  requests:
    memory: 1Gi

persistence: false

replicas: 2

topologyKey: "kubernetes.io/hostname"

podAntiAffinity: hard

backup:
#  pvcClaimName: ds-backup
  clusterName: sws-tom2
  verify: false

# If existing database is found then restore is always skipped
restore:
  enabled: false

# empty security context for Openshift
securityContext:
